import Head from "next/head";
import { useQuery } from "urql";
import { PRODUCT_QUERY } from "../lib/query";
import Product from "../components/Products";
import { Galery } from "../styles/galery";

export default function Home() {
  //Fetch products from Strapi
  const [results] = useQuery({ query: PRODUCT_QUERY });
  const { data, fetching, error } = results;

  //check for the data coming in
  if (fetching) return <p>Loading...</p>;
  if (error) return <p>Oh nooo...{error.message}</p>;
  const products = data.products.data;

  return (
    <div>
      <Head>
        <title>Styled Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello Next</h1>
        <Galery>
          {products.map((product) => (
            <Product key={product.attributes.slug} product={product} />
          ))}
        </Galery>
      </main>
    </div>
  );
}
